### ISSUE TITLE
Why Nauty sources are required to use external Nauty?

### ISSUE THREAD

**Issue by yurivict** [polymake/polymake#10]
Are Nauty headers+library not sufficient?

**Comment by benlorenz** [comment]
They should be sufficient, I will have a look if we can adjust this.
This option was probably not considered when the configuration scripts were written because nauty itself does not provide any installation targets in the makefile.

**Comment by yurivict** [comment]
> [...] nauty itself does not provide any installation targets in the makefile.

This is true, but ports often install such projects. At least the FreeBSD port and Arch ports do that,

**Comment by benlorenz** [comment]
Please try this patch: https://polymake.org/downloads/libnauty.patch
This allows passing `--with-nauty=/some/prefix` to `configure` and adds some autodetection for system-wide nauty installations. The output should look somewhat like this:
```
bundled extension nauty ... ok (version 26041 @ system)
```
If the autodetection fails (and no `--with-nauty=PATH` is given) it will fall back to the bundled version and show `(source: bundled)`.
Please post the contents of `build/bundled.log` if there are any unexpected errors.

PS: I hope that all those nauty-installation layouts do not differ too much, i.e. I am assuming that the headers live in a `/some/path/include/nauty/` directory.

**Comment by yurivict** [comment]
@benlorenz The patch works, thank you.

**Comment by benlorenz** [comment]
Thanks for testing, we will include this in the next polymake release.
