### ISSUE TITLE
GitHub release 4.11 missing assets

### ISSUE THREAD

**Issue by ryandesign** [polymake/polymake#15]
The [GitHub release 4.11](https://github.com/polymake/polymake/releases/tag/V4.11) is missing the assets polymake-4.11-minimal.tar.bz2 and polymake-4.11.tar.bz2. Previous [GitHub releases (e.g. 4.10)](https://github.com/polymake/polymake/releases/tag/V4.10) included these assets.

**Comment by benlorenz** [comment]
Sorry about that, I have added the tarballs now.
